name: "My First Wrtited docker Action"

on: 
  push:
   branches: 
   - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: "Hello World"
        uses: ozlevka/actions@test-action
        with:
          python-command: |
            import os
            import sys
            print(os.environ)
