name: "My First Wrtited docker Action"

on: 
  push:
   branches: 
   - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Hello World"
        uses: ozlevka/actions@test-action
        with:
          python-command: python -c "print('Here we run the python command')"